name: Browser tests
on:
    workflow_dispatch:
        inputs:
            send-success-notification:
                description: 'Send a notification when the tests pass'     
                required: false
                type: boolean
                default: true
    push:
        branches:
            - master
            - "[0-9]+.[0-9]+"
    pull_request: ~

jobs:
    regression-oss-setup1:
        name: "PHP 7.4/Node 14/PostgreSQL/Varnish/Redis"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "4.4.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            php-image: "ezsystems/php:7.4-v2-node14"
            job-count: 2
            timeout: 60
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
            AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
            AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
    regression-oss-setup2:
        name: "PHP 8.1/Node 16/MySQL/Compatibility layer"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "4.4.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            use-compatibility-layer: true
            job-count: 2
            timeout: 60
            php-image: "ezsystems/php:8.1-v2-node16"
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
            AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
            AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
