name: Browser tests
on:
    workflow_dispatch: ~
    push:
        branches:
            - master
            - "[0-9]+.[0-9]+"
    pull_request: ~

jobs:
    regression-oss-setup1:
        name: "PHP 7.4/PostgreSQL/Varnish/Redis"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "^4.0.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
            multirepository: true
            timeout: 40
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-oss-setup2:
        name: "PHP 7.4/MySQL/Compatibility layer"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "^4.0.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            multirepository: true
            use-compatibility-layer: true
            timeout: 40
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
