name: Browser tests
on:
    workflow_dispatch:
        inputs:
            send-success-notification:
                description: 'Send a notification when the tests pass'     
                required: false
                type: boolean
                default: true
    push:
        branches:
            - master
            - "[0-9]+.[0-9]+"
    pull_request: ~

jobs:
    regression-oss-setup1:
        name: "PHP 8.1/PostgreSQL/Varnish/Redis"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            ci-scripts-branch: "ibx-4516-node-18"
            project-edition: "oss"
            project-version: "^3.3.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            job-count: 2
            timeout: 60
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-oss-setup2:
        name: "PHP 7.3/MySQL"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "^3.3.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            php-image: "ghcr.io/ibexa/docker/php:7.3-node16"
            job-count: 2
            timeout: 60
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-oss-setup3:
        name: "PHP 7.4/MySQL"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: "^3.3.x-dev"
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            php-image: "ghcr.io/ibexa/docker/php:7.4-node18"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            job-count: 2
            timeout: 60
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
