name: Nightly browser tests
on:
    schedule:
        # Run tests every night
        - cron: "45 21 * * *"
    workflow_dispatch: ~

jobs:
    nightly:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 1
            matrix:
                repository:
                    - ibexa/oss
                    - ibexa/content
                    - ibexa/experience
                    - ibexa/commerce
                branch:
                    - "3.3"
                    - "4.5"
                    - "4.6"
                    - master
                include:
                    - repository: ibexa/headless
                      branch: "4.6"
                    - repository: ibexa/headless
                      branch: master
                    - repository: ibexa/example-in-memory-product-catalog
                      branch: "4.6"
                    - repository: ibexa/example-in-memory-product-catalog
                      branch: main
                exclude:
                    - repository: ibexa/content
                      branch: "4.6"
                    - repository: ibexa/content
                      branch: master
        steps:
            - uses: octokit/request-action@v2.x
              name: Trigger workflow
              with:
                  repository: ${{ matrix.repository }}
                  workflow: "browser-tests.yml"
                  ref: "!!str ${{ matrix.branch }}"
                  route: POST /repos/{repository}/actions/workflows/{workflow}/dispatches
                  inputs: '{ "send-success-notification": "false" }'
              env:
                  GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
